name: Test

on:
  pull_request:
    branches:
      - main
      - dev

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
  GITHUB_REPO: ${{github.repository}}

jobs:
  log:
    name: log var
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Search PR link
        run: |
          echo "${GITHUB_REPO}"
          echo "${GITHUB_PR_NUMBER}"
  test:
    name: changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Search PR link
        run: |
          grep -rni "${GITHUB_REPO}/pull/$GITHUB_PR_NUMBER" ./CHANGELOG.md || exit 1
